-- Operations integrity hardening. Apply after the family calendar auth migration.
create table if not exists public.calendar_admins (
  email text primary key check (email = lower(email)),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

insert into public.calendar_admins (email, active)
values
  ('josetomasayalams@gmail.com', true),
  ('scamussotomayor@gmail.com', true)
on conflict (email) do update set active = excluded.active;

alter table public.calendar_admins enable row level security;
revoke all on public.calendar_admins from anon, authenticated;

create or replace function public.is_calendar_admin()
returns boolean
language sql
stable
security definer
set search_path = public, auth
as $$
  select exists (
    select 1 from public.calendar_admins
    where email = lower(coalesce(auth.jwt() ->> 'email', ''))
      and active = true
  );
$$;
revoke all on function public.is_calendar_admin() from public, anon;
grant execute on function public.is_calendar_admin() to authenticated;

alter table public.rentals add column if not exists deleted_at timestamptz;
alter table public.cleanings add column if not exists deleted_at timestamptz;

create index if not exists rentals_active_dates_idx
  on public.rentals (checkin_date, checkout_date)
  where deleted_at is null;

drop index if exists public.cleanings_reservation_id_uidx;
create unique index cleanings_reservation_id_uidx
  on public.cleanings (reservation_id)
  where reservation_id is not null and deleted_at is null;

create unique index if not exists cleanings_rental_id_active_uidx
  on public.cleanings (rental_id)
  where rental_id is not null and deleted_at is null;

alter table public.rentals drop constraint if exists rentals_dates_chk;
alter table public.rentals
  add constraint rentals_dates_chk check (checkout_date > checkin_date);

create table if not exists public.calendar_change_log (
  id bigint generated by default as identity primary key,
  table_name text not null,
  record_id text not null,
  operation text not null check (operation in ('INSERT', 'UPDATE', 'DELETE')),
  actor_email text not null,
  before_data jsonb,
  after_data jsonb,
  changed_at timestamptz not null default now()
);

alter table public.calendar_change_log enable row level security;
revoke all on public.calendar_change_log from anon, authenticated;

create or replace function public.log_calendar_change()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  before_row jsonb;
  after_row jsonb;
  row_id text;
begin
  before_row := case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) else null end;
  after_row := case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) else null end;
  row_id := coalesce(after_row ->> 'id', before_row ->> 'id', 'unknown');
  insert into public.calendar_change_log (
    table_name, record_id, operation, actor_email, before_data, after_data
  ) values (
    tg_table_name,
    row_id,
    tg_op,
    lower(coalesce(auth.jwt() ->> 'email', current_user, 'system')),
    before_row,
    after_row
  );
  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;
revoke all on function public.log_calendar_change() from public, anon, authenticated;

create or replace function public.protect_calendar_change_log()
returns trigger
language plpgsql
as $$
begin
  raise exception 'calendar_change_log is append-only';
end;
$$;
revoke all on function public.protect_calendar_change_log() from public, anon, authenticated;

drop trigger if exists calendar_change_log_no_update on public.calendar_change_log;
create trigger calendar_change_log_no_update
  before update on public.calendar_change_log
  for each row execute function public.protect_calendar_change_log();

drop trigger if exists calendar_change_log_no_delete on public.calendar_change_log;
create trigger calendar_change_log_no_delete
  before delete on public.calendar_change_log
  for each row execute function public.protect_calendar_change_log();

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'rentals',
    'cleanings',
    'cleaning_comments',
    'beatriz_notification_batches',
    'beatriz_notifications',
    'beatriz_notification_events',
    'rodrigo_notification_batches',
    'rodrigo_notifications',
    'rodrigo_notification_events'
  ]
  loop
    execute format('drop trigger if exists %I_change_log_trg on public.%I', table_name, table_name);
    execute format(
      'create trigger %I_change_log_trg after insert or update or delete on public.%I for each row execute function public.log_calendar_change()',
      table_name,
      table_name
    );

    execute format('drop policy if exists "public read" on public.%I', table_name);
    execute format('drop policy if exists "public write" on public.%I', table_name);
    execute format('drop policy if exists "calendar admins read" on public.%I', table_name);
    execute format('drop policy if exists "calendar admins insert" on public.%I', table_name);
    execute format('drop policy if exists "calendar admins update" on public.%I', table_name);
    execute format('drop policy if exists "calendar admins delete" on public.%I', table_name);

    execute format(
      'create policy "calendar admins read" on public.%I for select to authenticated using (public.is_calendar_admin())',
      table_name
    );
    execute format(
      'create policy "calendar admins insert" on public.%I for insert to authenticated with check (public.is_calendar_admin())',
      table_name
    );
    execute format(
      'create policy "calendar admins update" on public.%I for update to authenticated using (public.is_calendar_admin()) with check (public.is_calendar_admin())',
      table_name
    );
    execute format(
      'create policy "calendar admins delete" on public.%I for delete to authenticated using (public.is_calendar_admin())',
      table_name
    );

    execute format('revoke all on public.%I from anon', table_name);
    execute format('grant select, insert, update, delete on public.%I to authenticated', table_name);
  end loop;
end;
$$;
